Better heartbeat checks in pod startup

diff --git a/src/main/resources/chipster-defaults.yaml b/src/main/resources/chipster-defaults.yaml
--- a/src/main/resources/chipster-defaults.yaml
+++ b/src/main/resources/chipster-defaults.yaml
@@ -290,73 +290,90 @@ scheduler-bash-heartbeat-script: |
   ps aux | grep SingleShotComp | grep $SESSION_ID | grep $JOB_ID  > logs/SingleShotComp-heartbeat.log 2>&1 &
   
 scheduler-bash-max-slots: "100"
-      # scheduler-bash-run-script: |
-      #   echo "start container, slots: $SLOTS, image: $IMAGE, sessionId: $SESSION_ID, jobId: $JOB_ID"
-      #   job_id=$(echo comp-job-$SESSION_ID-$JOB_ID | cut -c 1-63)
-      #   memory=$(( SLOTS*8 ))Gi
-      #   cpu=$(( SLOTS*2 ))
-      #   job_json=$(cat << EOF
-      #   apiVersion: batch/v1
-      #   kind: Job
-      #   metadata:
-      #     name: $job_id
-      #   spec:
-      #     template:
-      #       spec:
-      #         containers:
-      #         - name: comp-job
-      #           image: $IMAGE
-      #           imagePullPolicy: IfNotPresent
-      #           command: ["java",  "-cp", "lib/*:", "fi.csc.chipster.comp.SingleShotComp", "$SESSION_ID", "$JOB_ID"]
-      #           # resources:
-      #           #   limits:
-      #           #     cpu: $cpu
-      #           #     memory: $memory
-      #           #   requests:
-      #           #     cpu: $cpu
-      #           #     memory: $memory
-      #           volumeMounts:
-      #           - mountPath: /opt/chipster/conf
-      #             name: conf
-      #             readOnly: true
-      #           - mountPath: /opt/chipster/tools
-      #             name: tools-bin
-      #             readOnly: true
-      #           - mountPath: /opt/chipster/jobs-data
-      #             name: jobs-data
-      #         volumes:
-      #         - name: conf
-      #           secret:
-      #             defaultMode: 420
-      #             secretName: comp
-      #         - hostPath:
-      #             path: /mnt/tools-bin
-      #             type: Directory
-      #           name: tools-bin
-      #         - emptyDir: {}
-      #           name: jobs-data  
-      #         restartPolicy: Never
-      #     backoffLimit: 0
-      #   EOF
-      #   )
-      #   #echo "$job_json"
-      #   echo "$job_json" | kubectl --kubeconfig conf/kubeconfig apply -f -
-      # scheduler-bash-cancel-script: |
-      #   job_id=$(echo comp-job-$SESSION_ID-$JOB_ID | cut -c 1-63)
-      #   kubectl --kubeconfig conf/kubeconfig delete job $job_id
 
-      # scheduler-bash-finished-script: |
-      #   job_id=$(echo comp-job-$SESSION_ID-$JOB_ID | cut -c 1-63)
-      #   kubectl --kubeconfig conf/kubeconfig delete job $job_id
+#       scheduler-bash-run-script: |
+#         echo "start container, slots: $SLOTS, image: $IMAGE, sessionId: $SESSION_ID, jobId: $JOB_ID"
+#         job_id=$(echo comp-job-$SESSION_ID-$JOB_ID | cut -c 1-63)
+#         memory=$(( SLOTS*8 ))Gi
+#         cpu=$(( SLOTS*2 ))
+#         job_json=$(cat << EOF
+#         apiVersion: batch/v1
+#         kind: Job
+#         metadata:
+#           name: $job_id
+#         spec:
+#           template:
+#             spec:
+#               containers:
+#               - name: comp-job
+#                 image: $IMAGE
+#                 imagePullPolicy: IfNotPresent
+#                 command: ["java",  "-cp", "lib/*:", "fi.csc.chipster.comp.SingleShotComp", "$SESSION_ID", "$JOB_ID", "$SESSION_TOKEN", "$COMP_TOKEN"]
+#                 # resources:
+#                 #   limits:
+#                 #     cpu: $cpu
+#                 #     memory: $memory
+#                 #   requests:
+#                 #     cpu: $cpu
+#                 #     memory: $memory
+#                 volumeMounts:
+#                 - mountPath: /opt/chipster/conf
+#                   name: conf
+#                   readOnly: true
+#                 - mountPath: /opt/chipster/tools
+#                   name: tools-bin
+#                   readOnly: true
+#                 - mountPath: /opt/chipster/jobs-data
+#                   name: jobs-data
+#               volumes:
+#               - name: conf
+#                 secret:
+#                   defaultMode: 420
+#                   secretName: single-shot-comp
+#               - hostPath:
+#                   path: /mnt/tools-bin
+#                   type: Directory
+#                 name: tools-bin
+#               - emptyDir: {}
+#                 name: jobs-data  
+#               restartPolicy: Never
+#           backoffLimit: 0
+#         EOF
+#         )
+#         #echo "$job_json"
+#         echo "$job_json" | kubectl --kubeconfig conf/kubeconfig apply -f -
+#       scheduler-bash-cancel-script: |
+#         job_id=$(echo comp-job-$SESSION_ID-$JOB_ID | cut -c 1-63)
+#         kubectl --kubeconfig conf/kubeconfig delete job $job_id
 
-      # scheduler-bash-heartbeat-script: |
-      #   job_id=$(echo comp-job-$SESSION_ID-$JOB_ID | cut -c 1-63)
-      #   json=$(kubectl --kubeconfig conf/kubeconfig get job $job_id -o json)
-      #   if [ -n "$json" ]; then
-      #     [ $(echo $json | jq .status.active) == 1 ]
-      #   else
-      #     exit 1
-      #   fi
+#       scheduler-bash-finished-script: |
+#         job_id=$(echo comp-job-$SESSION_ID-$JOB_ID | cut -c 1-63)
+#         kubectl --kubeconfig conf/kubeconfig delete job $job_id
+
+#       scheduler-bash-heartbeat-script: |
+#         job_id=$(echo comp-job-$SESSION_ID-$JOB_ID | cut -c 1-63)
+#         json=$(kubectl --kubeconfig conf/kubeconfig get pod -l job-name=$job_id -o json | jq .items[0].status.containerStatuses[0].state)
+#         if [ "$json" == null ]; then
+#           echo "pod not found"
+#           exit 1
+#         fi
+#         running_state=$(echo "$json" | jq .running -r)
+#         if [ "$running_state" != null ]; then
+#           echo "pod is running"
+#           exit 0
+#         fi
+#         terminated_reason=$(echo "$json" | jq .terminated.reason -r)
+#         if [ "$terminated_reason" != null ]; then
+#           echo "pod has terminated: $terminated_reason"
+#           exit 1
+#         fi
+#         waiting_reason=$(echo "$json" | jq .waiting.reason -r)
+#         if [ "$waiting_reason" != null ]; then
+#           echo "pod is waiting: $waiting_reason"
+#           exit 1
+#         fi
+#         echo "unknown pod status: $json"
+#         exit 1
       
 # how often to check if BashJobScheduler jobs are alive
 scheduler-bash-job-timer-interval: 10
